# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'Terraform/**'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run:  pip install -r requirements.txt
    - name: Build Docker image
      run: docker build  -t python-docker .
    - name : Tag Docker Image 
      run : docker tag python-docker dummytest.azurecr.io/python:${{github.run_number}}
     # Push Image To ACR
    - name : Push Docker Image to ACR
      run: docker push dummytest.azurecr.io/python:${{github.run_number}}

  deploy:
     needs: build
     runs-on: ubuntu-latest
     environment: Test
     steps:
     - uses: actions/checkout@v4
     - name : Azure CLI Login
       working-directory: .
       run: az login --service-principal -u ${{ secrets.SPAPPID }} -p ${{ secrets.SPPassword }} --tenant ${{ secrets.TenantID }}
     - name: Add AKS to CMD Contiext 
       run: az aks get-credentials --name ${{ secrets.AKSNAME }} --resource-group ${{ secrets.RG }}
       
     - name: Var_Substitution
       uses: microsoft/variable-substitution@v1
       with:
        files:  deployment.yaml
            
     - name: Deploy To AKS 
       run : kubectl apply -f deployment.yaml
     
   
    
